import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelNett - Software para Turismo",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-travel.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className} min-h-screen fondo text-primary antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
